[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/services.html"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/blog.html"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/case-studies.html"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/case-studies/*"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200